# Generated by Django 3.1 on 2021-01-15 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corecode', '0004_auto_20201124_0614'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AcademicSession',
        ),
        migrations.DeleteModel(
            name='AcademicTerm',
        ),
        migrations.DeleteModel(
            name='SiteConfig',
        ),
        migrations.DeleteModel(
            name='StudentClass',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
