# Generated by Django 3.1 on 2021-01-08 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0008_auto_20210108_0721'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='unit',
        ),
    ]
