# Generated by Django 3.1 on 2021-01-08 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0009_remove_product_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stored_location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
