# Generated by Django 3.1 on 2021-01-09 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0010_product_stored_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Quantity',
            field=models.CharField(blank=True, default=0, max_length=100, null=True),
        ),
    ]
