# Generated by Django 3.1 on 2021-01-11 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0011_auto_20210109_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Quantity',
            field=models.FloatField(blank=True, default=0, max_length=100, null=True),
        ),
    ]
